from __future__ import annotations

from .sources import PublicWeldKnowledgeBase, PublicWeldSource, SourceType, UsableFor


def load_seed_knowledge_base() -> PublicWeldKnowledgeBase:
    sources = [
        PublicWeldSource(
            source_id="vendor-hyundai-welding-cobot-shipbuilding-2024",
            source_type=SourceType.VENDOR_CASE,
            title="Hyundai Welding Cobot Solution (Shipbuilding) Leaflet 2024",
            url="https://www.hyundaiwelding.com/data/file/download/brochures/Hyundai_Welding_Cobot%20Solution%20%28Shipbuilding%29_Leaflet_2024.pdf",
            publisher="Hyundai Welding",
            shipbuilding_relevance="Shipbuilding cobot welding scenario reference.",
            covered_fields=["shipbuilding_context", "robot_welding_application"],
            missing_fields=["trajectory", "process_signal", "quality_result"],
            usable_for=[UsableFor.SCENARIO_SELECTION],
            source_refs=["design-spec-section-7.1"],
            assumptions=["Use for task-family discovery only."],
            notes="No direct production data imported.",
        ),
        PublicWeldSource(
            source_id="vendor-kobelco-shipbuilding-welding",
            source_type=SourceType.PROCESS_GUIDE,
            title="KOBELCO Shipbuilding Welding Industry Page",
            url="https://www.kobelco.co.jp/english/products/welding/industries/shipbuilding.html",
            publisher="Kobe Steel / KOBELCO",
            shipbuilding_relevance="Lists shipbuilding welding stages and weld objects.",
            covered_fields=["shipbuilding_context", "weld_position", "joint_family"],
            missing_fields=["trajectory", "process_signal"],
            usable_for=[UsableFor.SCENARIO_SELECTION, UsableFor.PARAMETER_RANGE],
            source_refs=["design-spec-section-4.1", "design-spec-section-7.1"],
            assumptions=["Use stage and weld-object terms as public constraints."],
            notes="Does not validate project simulation outputs.",
        ),
        PublicWeldSource(
            source_id="case-siemens-hd-hyundai-mipo-autonomous-welding",
            source_type=SourceType.VENDOR_CASE,
            title="HD Hyundai Mipo Autonomous Welding Robot Development Case",
            url="https://resources.sw.siemens.com/en-US/case-study-hd-hyundai-mipo/",
            publisher="Siemens",
            shipbuilding_relevance="References subassembly welding, block constraints, simulation and robot programs.",
            covered_fields=["shipbuilding_context", "robot_program_simulation", "confined_space_context"],
            missing_fields=["weld_parameters", "quality_result"],
            usable_for=[UsableFor.SCENARIO_SELECTION],
            source_refs=["design-spec-section-4.1", "design-spec-section-7.1"],
            assumptions=["Use as public case evidence for shipbuilding task decomposition."],
            notes="No robot program or customer process data imported.",
        ),
        PublicWeldSource(
            source_id="vendor-kranendonk-panel-welding-gantry",
            source_type=SourceType.VENDOR_CASE,
            title="KRANENDONK Shipbuilding Panel Welding Gantry",
            url="https://www.kranendonk.com/solutions/shipbuilding/panel-welding-gantry/",
            publisher="KRANENDONK",
            shipbuilding_relevance="Panel welding automation for large stiffened panels.",
            covered_fields=["shipbuilding_context", "stiffened_panel", "torch_angle", "travel_speed", "stitch_pattern"],
            missing_fields=["process_signal", "quality_result"],
            usable_for=[UsableFor.SCENARIO_SELECTION, UsableFor.PARAMETER_RANGE],
            source_refs=["design-spec-section-4.1", "design-spec-section-7.1"],
            assumptions=["Use as scenario and field coverage reference."],
            notes="No controller data imported.",
        ),
        PublicWeldSource(
            source_id="dataset-gdxray-weld-xray",
            source_type=SourceType.DATASET,
            title="GDXray Weld X-ray Dataset",
            url="https://github.com/computervision-xray-testing/GDXray",
            publisher="Computer Vision X-Ray Testing repository",
            shipbuilding_relevance="Generic weld defect image labels can inform quality label vocabulary.",
            covered_fields=["quality_label", "defect_label"],
            missing_fields=["shipbuilding_context", "trajectory", "process_signal"],
            usable_for=[UsableFor.QUALITY_LABEL, UsableFor.BENCHMARK],
            source_refs=["design-spec-section-7.2"],
            assumptions=["Use only for defect vocabulary and benchmark orientation."],
            notes="Not proof of shipbuilding task quality.",
        ),
        PublicWeldSource(
            source_id="dataset-zenodo-metal-arc-welding-10017718",
            source_type=SourceType.DATASET,
            title="Zenodo Metal Arc Welding Dataset",
            url="https://zenodo.org/records/10017718",
            publisher="Zenodo",
            shipbuilding_relevance="Generic arc welding data source for field coverage review.",
            covered_fields=["process_reference", "measurement_artifact"],
            missing_fields=["shipbuilding_context", "robot_trajectory"],
            usable_for=[UsableFor.PARAMETER_RANGE, UsableFor.BENCHMARK],
            source_refs=["design-spec-section-7.2"],
            assumptions=["Screen exact files before using any field in scenarios."],
            notes="Use as candidate public data source, not validation.",
        ),
        PublicWeldSource(
            source_id="standard-aws-swps-public-page",
            source_type=SourceType.STANDARD,
            title="AWS Standard Welding Procedure Specifications Public Page",
            url="https://www.aws.org/about/get-involved/committees/b2-committee-on-procedure-and-performance-qualification/swps/",
            publisher="American Welding Society",
            shipbuilding_relevance="Public WPS concept and variable reference for process constraints.",
            covered_fields=["process_variable", "procedure_reference"],
            missing_fields=["shipbuilding_context", "trajectory"],
            usable_for=[UsableFor.PARAMETER_RANGE],
            source_refs=["design-spec-section-7.3"],
            assumptions=["Use public page as WPS concept reference only."],
            notes="Does not replace project or customer WPS.",
        ),
        PublicWeldSource(
            source_id="project-260522-shipbuilding-welding-brain-plan",
            source_type=SourceType.PROCESS_GUIDE,
            title="船舶焊接工艺大脑平台整体规划方案",
            url="docs/project/船舶焊接工艺大脑平台整体规划方案.html",
            publisher="project internal",
            shipbuilding_relevance="Defines project-specific weld objects, groove geometry, trajectory objects, and quality objects.",
            covered_fields=["shipbuilding_context", "weld_object", "groove_geometry", "trajectory_object", "quality_object"],
            missing_fields=["public_dataset", "real_machine_validation"],
            usable_for=[UsableFor.SCENARIO_SELECTION, UsableFor.PARAMETER_RANGE, UsableFor.QUALITY_LABEL],
            source_refs=["design-spec-section-3", "design-spec-section-4"],
            assumptions=["Use as project planning source, not real measured data."],
            notes="Internal planning document.",
        ),
    ]
    return PublicWeldKnowledgeBase(sources)
