from __future__ import annotations

from .shipbuilding import (
    ShipbuildingTaskFamily,
    TaskDisposition,
    WeldJointType,
    WeldPosition,
)
from .sources import PublicWeldKnowledgeBase, PublicWeldSource, SourceType, UsableFor


def load_seed_knowledge_base() -> PublicWeldKnowledgeBase:
    sources = [
        PublicWeldSource(
            source_id="vendor-hyundai-welding-cobot-shipbuilding-2024",
            source_type=SourceType.VENDOR_CASE,
            title="Hyundai Welding Cobot Solution (Shipbuilding) Leaflet 2024",
            url="https://www.hyundaiwelding.com/data/file/download/brochures/Hyundai_Welding_Cobot%20Solution%20%28Shipbuilding%29_Leaflet_2024.pdf",
            publisher="Hyundai Welding",
            shipbuilding_relevance="Shipbuilding cobot welding scenario reference.",
            covered_fields=["shipbuilding_context", "robot_welding_application"],
            missing_fields=["trajectory", "process_signal", "quality_result"],
            usable_for=[UsableFor.SCENARIO_SELECTION],
            source_refs=["design-spec-section-7.1"],
            assumptions=["Use for task-family discovery only."],
            notes="No direct production data imported.",
        ),
        PublicWeldSource(
            source_id="vendor-kobelco-shipbuilding-welding",
            source_type=SourceType.PROCESS_GUIDE,
            title="KOBELCO Shipbuilding Welding Industry Page",
            url="https://www.kobelco.co.jp/english/products/welding/industries/shipbuilding.html",
            publisher="Kobe Steel / KOBELCO",
            shipbuilding_relevance="Lists shipbuilding welding stages and weld objects.",
            covered_fields=["shipbuilding_context", "weld_position", "joint_family"],
            missing_fields=["trajectory", "process_signal"],
            usable_for=[UsableFor.SCENARIO_SELECTION, UsableFor.PARAMETER_RANGE],
            source_refs=["design-spec-section-4.1", "design-spec-section-7.1"],
            assumptions=["Use stage and weld-object terms as public constraints."],
            notes="Does not validate project simulation outputs.",
        ),
        PublicWeldSource(
            source_id="case-siemens-hd-hyundai-mipo-autonomous-welding",
            source_type=SourceType.VENDOR_CASE,
            title="HD Hyundai Mipo Autonomous Welding Robot Development Case",
            url="https://resources.sw.siemens.com/en-US/case-study-hd-hyundai-mipo/",
            publisher="Siemens",
            shipbuilding_relevance="References subassembly welding, block constraints, simulation and robot programs.",
            covered_fields=["shipbuilding_context", "robot_program_simulation", "confined_space_context"],
            missing_fields=["weld_parameters", "quality_result"],
            usable_for=[UsableFor.SCENARIO_SELECTION],
            source_refs=["design-spec-section-4.1", "design-spec-section-7.1"],
            assumptions=["Use as public case evidence for shipbuilding task decomposition."],
            notes="No robot program or customer process data imported.",
        ),
        PublicWeldSource(
            source_id="vendor-kranendonk-panel-welding-gantry",
            source_type=SourceType.VENDOR_CASE,
            title="KRANENDONK Shipbuilding Panel Welding Gantry",
            url="https://www.kranendonk.com/solutions/shipbuilding/panel-welding-gantry/",
            publisher="KRANENDONK",
            shipbuilding_relevance="Panel welding automation for large stiffened panels.",
            covered_fields=["shipbuilding_context", "stiffened_panel", "torch_angle", "travel_speed", "stitch_pattern"],
            missing_fields=["process_signal", "quality_result"],
            usable_for=[UsableFor.SCENARIO_SELECTION, UsableFor.PARAMETER_RANGE],
            source_refs=["design-spec-section-4.1", "design-spec-section-7.1"],
            assumptions=["Use as scenario and field coverage reference."],
            notes="No controller data imported.",
        ),
        PublicWeldSource(
            source_id="dataset-gdxray-weld-xray",
            source_type=SourceType.DATASET,
            title="GDXray Weld X-ray Dataset",
            url="https://github.com/computervision-xray-testing/GDXray",
            publisher="Computer Vision X-Ray Testing repository",
            shipbuilding_relevance="Generic weld defect image labels can inform quality label vocabulary.",
            covered_fields=["quality_label", "defect_label"],
            missing_fields=["shipbuilding_context", "trajectory", "process_signal"],
            usable_for=[UsableFor.QUALITY_LABEL, UsableFor.BENCHMARK],
            source_refs=["design-spec-section-7.2"],
            assumptions=["Use only for defect vocabulary and benchmark orientation."],
            notes="Not proof of shipbuilding task quality.",
        ),
        PublicWeldSource(
            source_id="dataset-zenodo-metal-arc-welding-10017718",
            source_type=SourceType.DATASET,
            title="Zenodo Metal Arc Welding Dataset",
            url="https://zenodo.org/records/10017718",
            publisher="Zenodo",
            shipbuilding_relevance="Generic arc welding data source for field coverage review.",
            covered_fields=["process_reference", "measurement_artifact"],
            missing_fields=["shipbuilding_context", "robot_trajectory"],
            usable_for=[UsableFor.PARAMETER_RANGE, UsableFor.BENCHMARK],
            source_refs=["design-spec-section-7.2"],
            assumptions=["Screen exact files before using any field in scenarios."],
            notes="Use as candidate public data source, not validation.",
        ),
        PublicWeldSource(
            source_id="standard-aws-swps-public-page",
            source_type=SourceType.STANDARD,
            title="AWS Standard Welding Procedure Specifications Public Page",
            url="https://www.aws.org/about/get-involved/committees/b2-committee-on-procedure-and-performance-qualification/swps/",
            publisher="American Welding Society",
            shipbuilding_relevance="Public WPS concept and variable reference for process constraints.",
            covered_fields=["process_variable", "procedure_reference"],
            missing_fields=["shipbuilding_context", "trajectory"],
            usable_for=[UsableFor.PARAMETER_RANGE],
            source_refs=["design-spec-section-7.3"],
            assumptions=["Use public page as WPS concept reference only."],
            notes="Does not replace project or customer WPS.",
        ),
        PublicWeldSource(
            source_id="encyclopedia-wartsila-weld-defects",
            source_type=SourceType.PROCESS_GUIDE,
            title="Wartsila Encyclopedia: Weld defects",
            url="https://www.wartsila.com/encyclopedia/term/weld-defects",
            publisher="Wartsila",
            shipbuilding_relevance="Marine engineering encyclopedia term for weld defects with hull weld inspection references.",
            covered_fields=["quality_label", "defect_label", "inspection_reference"],
            missing_fields=["shipbuilding_context", "trajectory", "process_signal"],
            usable_for=[UsableFor.QUALITY_LABEL, UsableFor.BENCHMARK],
            source_refs=["design-spec-section-7.2"],
            assumptions=["Use only for defect vocabulary and inspection-reference orientation."],
            notes="Public reference material, not project-specific validation evidence.",
        ),
        PublicWeldSource(
            source_id="project-260522-shipbuilding-welding-brain-plan",
            source_type=SourceType.PROCESS_GUIDE,
            title="船舶焊接工艺大脑平台整体规划方案",
            url="docs/project/船舶焊接工艺大脑平台整体规划方案.html",
            publisher="project internal",
            shipbuilding_relevance="Defines project-specific weld objects, groove geometry, trajectory objects, and quality objects.",
            covered_fields=["shipbuilding_context", "weld_object", "groove_geometry", "trajectory_object", "quality_object"],
            missing_fields=["public_dataset", "real_machine_validation"],
            usable_for=[UsableFor.SCENARIO_SELECTION, UsableFor.PARAMETER_RANGE, UsableFor.QUALITY_LABEL],
            source_refs=["design-spec-section-3", "design-spec-section-4"],
            assumptions=["Use as project planning source, not real measured data."],
            notes="Internal planning document.",
        ),
    ]
    return PublicWeldKnowledgeBase(sources)


def load_seed_task_families() -> list[ShipbuildingTaskFamily]:
    return [
        ShipbuildingTaskFamily(
            family_id="stiffened-panel-fillet",
            name="加筋板/纵骨角焊",
            shipbuilding_context="panel line, small assembly, stiffener-to-plate welding",
            typical_weld_objects=["stiffener-to-plate", "longitudinal-to-panel", "web-to-panel"],
            joint_types=[WeldJointType.FILLET, WeldJointType.TEE],
            positions=[WeldPosition.FLAT, WeldPosition.HORIZONTAL],
            modeling_difficulty=1,
            required_fields=["stiffened_panel", "torch_angle", "travel_speed"],
            assumption_fields=["leg_size_mm", "plate_thickness_mm"],
            source_ids=[
                "vendor-kranendonk-panel-welding-gantry",
                "project-260522-shipbuilding-welding-brain-plan",
            ],
            disposition=TaskDisposition.CANDIDATE,
            notes="First candidate because it is shipbuilding-specific and geometry is tractable.",
        ),
        ShipbuildingTaskFamily(
            family_id="panel-butt",
            name="平面板拼接/简化对接焊",
            shipbuilding_context="panel line and flat block plate joining",
            typical_weld_objects=["bottom shell butt", "tank top butt", "deck butt", "side shell butt"],
            joint_types=[WeldJointType.BUTT],
            positions=[WeldPosition.FLAT, WeldPosition.HORIZONTAL],
            modeling_difficulty=2,
            required_fields=["shipbuilding_context", "groove_geometry"],
            assumption_fields=["plate_thickness_mm", "root_gap_mm", "travel_speed"],
            source_ids=[
                "vendor-kobelco-shipbuilding-welding",
                "project-260522-shipbuilding-welding-brain-plan",
            ],
            disposition=TaskDisposition.CANDIDATE,
            notes="Candidate, but must be distinguished from generic straight-flat welding.",
        ),
        ShipbuildingTaskFamily(
            family_id="micro-panel-web-bulkhead",
            name="微型面板/腹板/隔板多短焊缝",
            shipbuilding_context="subassembly welding for web, bulkhead, bracket and small stiffened structures",
            typical_weld_objects=["web fillet", "bulkhead fillet", "bracket lap", "short seam sequence"],
            joint_types=[WeldJointType.FILLET, WeldJointType.LAP, WeldJointType.TEE],
            positions=[WeldPosition.FLAT, WeldPosition.HORIZONTAL],
            modeling_difficulty=2,
            required_fields=["shipbuilding_context"],
            assumption_fields=["weld_seam_list", "sequence_order", "node_transition", "torch_angle_deg"],
            source_ids=[
                "case-siemens-hd-hyundai-mipo-autonomous-welding",
                "project-260522-shipbuilding-welding-brain-plan",
            ],
            disposition=TaskDisposition.CANDIDATE,
            notes="Candidate for multi-seam sequence before confined-space block welding.",
        ),
        ShipbuildingTaskFamily(
            family_id="double-bottom-inner-fillet",
            name="双层底/双壳内部角焊",
            shipbuilding_context="double bottom, double hull, block cell internal welding",
            typical_weld_objects=["inner double-hull fillet", "double-bottom inside fillet"],
            joint_types=[WeldJointType.FILLET],
            positions=[WeldPosition.HORIZONTAL, WeldPosition.VERTICAL_UP],
            modeling_difficulty=3,
            required_fields=["shipbuilding_context", "weld_position", "confined_space_context"],
            assumption_fields=["pose_segment", "reachability_placeholder"],
            source_ids=[
                "vendor-kobelco-shipbuilding-welding",
                "case-siemens-hd-hyundai-mipo-autonomous-welding",
            ],
            disposition=TaskDisposition.PROBE,
            notes="Strong shipbuilding relevance, but better as a second-round probe.",
        ),
        ShipbuildingTaskFamily(
            family_id="vertical-overhead-block-weld",
            name="立向/仰位船体焊缝",
            shipbuilding_context="block assembly and erection stage",
            typical_weld_objects=["side shell vertical butt", "overhead butt", "vertical-up fillet"],
            joint_types=[WeldJointType.BUTT, WeldJointType.FILLET],
            positions=[WeldPosition.VERTICAL_UP, WeldPosition.OVERHEAD],
            modeling_difficulty=4,
            required_fields=["weld_position"],
            assumption_fields=["position_specific_parameters", "pose_constraints", "operator_review"],
            source_ids=[
                "vendor-kobelco-shipbuilding-welding",
                "project-260522-shipbuilding-welding-brain-plan",
            ],
            disposition=TaskDisposition.DEFER,
            notes="Defer until easier flat/horizontal scenarios are stable.",
        ),
        ShipbuildingTaskFamily(
            family_id="thick-plate-groove-multipass",
            name="厚板坡口多层多道",
            shipbuilding_context="block assembly, grand assembly and erection welds",
            typical_weld_objects=["V groove", "X groove", "K groove", "long thick-plate butt weld"],
            joint_types=[WeldJointType.GROOVE, WeldJointType.BUTT],
            positions=[WeldPosition.MULTI_POSITION],
            modeling_difficulty=4,
            required_fields=["groove_geometry", "procedure_reference"],
            assumption_fields=["layer_pass_plan", "interpass_constraints"],
            source_ids=[
                "project-260522-shipbuilding-welding-brain-plan",
                "standard-aws-swps-public-page",
            ],
            disposition=TaskDisposition.DEFER,
            notes="Important roadmap item, not first-batch lightweight simulation.",
        ),
        ShipbuildingTaskFamily(
            family_id="curved-complex-seams",
            name="曲面与空间复杂焊缝",
            shipbuilding_context="curved shell plate and complex node welding",
            typical_weld_objects=["curved seam", "cross node", "bracket intersection"],
            joint_types=[WeldJointType.COMPLEX],
            positions=[WeldPosition.MULTI_POSITION],
            modeling_difficulty=5,
            required_fields=["shipbuilding_context"],
            assumption_fields=["curved_centerline", "multi_joint_topology", "cad_reference"],
            source_ids=[
                "project-260522-shipbuilding-welding-brain-plan",
                "case-siemens-hd-hyundai-mipo-autonomous-welding",
            ],
            disposition=TaskDisposition.DEFER,
            notes="Defer because modeling complexity is too high for the current stage, despite high-level source support.",
        ),
    ]
